name: Back-end CI

on:
  push:
    paths: ['backend/**']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
        cache: maven
    - name: Build & unit-test
      run: |
        cd backend
        ./mvnw -B verify
    - name: Build Docker image
      run: |
        cd backend
        ./mvnw -DskipTests package
        docker build -t ${{ secrets.DOCKER_REPO }}/study-backend:${{ github.sha }} .
