name: Render CD

on:
  push:
    branches: [main]
    paths: [.github/workflows/render.yml]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Trigger Render deploy
      uses: JohnBeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID_FRONT }}
        api-key: ${{ secrets.RENDER_API_KEY }}

  deploy-backend:
    runs-on: ubuntu-latest
    needs: deploy-frontend
    steps:
    - uses: actions/checkout@v4
    - name: Trigger Render deploy
      uses: JohnBeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID_BACK }}
        api-key: ${{ secrets.RENDER_API_KEY }}